name: ci

on:
  push:
    branches: ['**']
  pull_request:
    branches: [dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: alpine:edge
    steps:
    - name: Add pacakges
      run: |
        apk update
        apk upgrade
        apk add --no-cache clang clang-tidy clang-format make cmake>4.1.2
    - uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Format
      run: make format
