name: CI
description: 'Workflow to build, lint and format'

on:
    push:
        branches: ['**']
    pull_request:
        types: [opened, reopened]
        branches: ['**']

jobs:
    ci:
        runs-on: ubuntu-latest
        container: alpine:edge
        steps:
            - name: Setup aline:edge container
              uses: ./.github/actions/setup.yml
            - uses: actions/checkout@v4
            - name: Build
              run: make build
            - name: Lint
              run: make lint
            - name: Format
              run: make format
